import React, { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { Skeleton } from '../components/ui/Skeleton';
import { Users, CreditCard, Calendar, Activity, TrendingUp, AlertCircle, Clock } from 'lucide-react';
import api from '../api/axios';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import { Button } from '../components/ui/Button';

import { toast } from 'sonner';

// Icon mapping helper
const iconMap = {
    "Total Patients": Users,
    "Revenue": CreditCard,
    "Appointments": Calendar,
    "Pending Invoices": Activity
};

const MOCK_REVENUE_DATA = [
    { name: 'Mon', revenue: 12000 },
    { name: 'Tue', revenue: 19000 },
    { name: 'Wed', revenue: 15000 },
    { name: 'Thu', revenue: 22000 },
    { name: 'Fri', revenue: 28000 },
    { name: 'Sat', revenue: 14000 },
    { name: 'Sun', revenue: 8000 },
];

const MOCK_APPOINTMENT_DATA = [
    { name: '9AM', patients: 4 },
    { name: '10AM', patients: 8 },
    { name: '11AM', patients: 12 },
    { name: '12PM', patients: 6 },
    { name: '1PM', patients: 9 },
    { name: '2PM', patients: 15 },
    { name: '3PM', patients: 10 },
];

import { useAuth } from '../context/AuthContext';

export default function Dashboard() {
    const { user } = useAuth();
    const [stats, setStats] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchStats = async () => {
            try {
                setLoading(true);
                const response = await api.get('/dashboard/stats');
                setStats(response.data);
            } catch (err) {
                console.error("Dashboard fetch error:", err);
                const errMsg = err.response?.data?.message || err.message;
                setError(`API connection unavailable (${errMsg}) - Using simulated data`);
                // Mock fallback
                setStats([
                    { title: "Total Patients", value: "1,284", change: "+12% from last month", color: "text-blue-600" },
                    { title: "Revenue", value: "$42,500", change: "+8.4% from last month", color: "text-green-600" },
                    { title: "Appointments", value: "48", change: "-3% from yesterday", color: "text-purple-600" },
                    { title: "Pending Invoices", value: "12", change: "Action required", color: "text-red-600" }
                ]);
            } finally {
                setLoading(false);
            }
        };

        fetchStats();
    }, []);

    const handleDownloadReport = () => {
        if (!stats) return;

        // Using mock data for the report as the actual `stats` state is an array of objects,
        // not a single object with properties like totalPatients, newAppointments, etc.
        // This assumes a structure for `stats` that would be returned by a successful API call.
        const mockReportStats = {
            totalPatients: "1,284",
            newAppointments: "48",
            criticalCases: "3",
            totalRevenue: 42500,
            revenueData: [
                { month: 'Jan', revenue: 10000 },
                { month: 'Feb', revenue: 12000 },
                { month: 'Mar', revenue: 15000 },
            ],
            recentAlerts: [
                { time: "10 mins ago", msg: "Low Inventory: Paracetamol" },
                { time: "2 hours ago", msg: "New Specialist Added" },
            ]
        };

        const reportData = `
MEDI-FLOW AI PERFORMANCE REPORT
==============================
Date: ${new Date().toLocaleString()}

KEY METRICS:
- Total Patients: ${mockReportStats.totalPatients}
- Today's Appointments: ${mockReportStats.newAppointments}
- Critical Cases: ${mockReportStats.criticalCases}
- Revenue (Actual/Projected): $${mockReportStats.totalRevenue.toLocaleString()}

MONTHLY REVENUE BREAKDOWN:
${mockReportStats.revenueData.map(d => `${d.month}: $${d.revenue.toLocaleString()}`).join('\n')}

RECENT ALERTS:
${mockReportStats.recentAlerts.map(a => `[${a.time}] ${a.msg}`).join('\n')}

Generated by MediFlow AI (Hospital Management Suite)
        `.trim();

        const blob = new Blob([reportData], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `MediFlow_Report_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);

        toast.success("Professional report generated and downloaded.");
    };

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            {/* Header section with KPIs and Download Report */}
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div>
                    <h2 className="text-3xl font-bold tracking-tight text-gray-900">Health Monitoring Dashboard</h2>
                    <p className="text-gray-500 italic">Real-time clinical insights powered by MediFlow AI.</p>
                </div>
                <div className="flex items-center gap-3">
                    <Button
                        className="gap-2 bg-primary hover:bg-primary/90 text-white shadow-md transition-all active:scale-95"
                        onClick={handleDownloadReport}
                    >
                        <TrendingUp className="h-4 w-4" />
                        Download Report
                    </Button>
                </div>
            </div>

            {/* Error Banner (if any) */}
            {error && (
                <div className="flex items-center gap-3 rounded-lg border border-yellow-200 bg-yellow-50 p-4 text-yellow-800">
                    <AlertCircle className="h-5 w-5" />
                    <p className="text-sm font-medium">{error}</p>
                </div>
            )}

            {/* KPI Grid */}
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
                {stats.length > 0 && stats.map((stat, i) => {
                    const Icon = iconMap[stat.title] || Activity;
                    return (
                        <Card key={i} className="transition-all hover:shadow-md border-gray-200 bg-white shadow-sm">
                            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                                <CardTitle className="text-sm font-medium text-gray-500 uppercase tracking-wider">
                                    {stat.title}
                                </CardTitle>
                                <div className={`rounded-full p-2 bg-gray-50 ${stat.color}`}>
                                    <Icon className="h-4 w-4" />
                                </div>
                            </CardHeader>
                            <CardContent>
                                <div className="text-2xl font-bold text-gray-900">{stat.value}</div>
                                <p className="text-xs text-gray-500 mt-1 font-medium">
                                    {stat.change}
                                </p>
                            </CardContent>
                        </Card>
                    );
                })}
            </div>

            {/* Charts Section */}
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-7">
                {/* Main Revenue Chart */}
                <Card className="col-span-4 border-gray-200 bg-white shadow-sm">
                    <CardHeader>
                        <CardTitle className="text-lg font-semibold text-gray-900">Revenue Analytics</CardTitle>
                        <p className="text-sm text-gray-500">Weekly revenue performance</p>
                    </CardHeader>
                    <CardContent className="pl-0">
                        <div className="h-[350px] w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={MOCK_REVENUE_DATA}>
                                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                                    <XAxis
                                        dataKey="name"
                                        axisLine={false}
                                        tickLine={false}
                                        tick={{ fill: '#6B7280', fontSize: 12 }}
                                        dy={10}
                                    />
                                    <YAxis
                                        axisLine={false}
                                        tickLine={false}
                                        tick={{ fill: '#6B7280', fontSize: 12 }}
                                        tickFormatter={(value) => `$${value}`}
                                    />
                                    <Tooltip
                                        cursor={{ fill: '#F3F4F6' }}
                                        contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                                    />
                                    <Bar dataKey="revenue" fill="#2563EB" radius={[6, 6, 0, 0]} barSize={40} />
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    </CardContent>
                </Card>

                {/* Patient Traffic / Recent Activity */}
                <Card className="col-span-3 border-gray-200 bg-white shadow-sm">
                    <CardHeader>
                        <CardTitle className="text-lg font-semibold text-gray-900">Today's Traffic</CardTitle>
                        <p className="text-sm text-gray-500">Patient check-ins by hour</p>
                    </CardHeader>
                    <CardContent>
                        <div className="h-[200px] w-full mb-6">
                            <ResponsiveContainer width="100%" height="100%">
                                <LineChart data={MOCK_APPOINTMENT_DATA}>
                                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                                    <XAxis dataKey="name" hide />
                                    <Tooltip contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                                    <Line type="monotone" dataKey="patients" stroke="#10B981" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 6 }} />
                                </LineChart>
                            </ResponsiveContainer>
                        </div>

                        <div className="space-y-6">
                            <h4 className="text-sm font-semibold text-gray-900 uppercase tracking-wider">Recent Alerts</h4>
                            {[
                                { title: "Low Inventory: Paracetamol", time: "10 mins ago", type: "warning" },
                                { title: "New Specialist Added", time: "2 hours ago", type: "info" },
                                { title: "Insurance Claim #402 Rejected", time: "5 hours ago", type: "error" }
                            ].map((alert, i) => (
                                <div key={i} className="flex items-start gap-3">
                                    <div className={`mt-0.5 rounded-full p-1.5 ${alert.type === 'warning' ? 'bg-yellow-100 text-yellow-600' :
                                        alert.type === 'error' ? 'bg-red-100 text-red-600' :
                                            'bg-blue-100 text-blue-600'
                                        }`}>
                                        <AlertCircle className="h-4 w-4" />
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-sm font-medium leading-none text-gray-900">{alert.title}</p>
                                        <div className="flex items-center gap-1 text-xs text-gray-500">
                                            <Clock className="h-3 w-3" />
                                            {alert.time}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div >
    );
}
